const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    //admin
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    //Allcode
    GET_ALLCODE_BY_TYPE_START: 'GET_ALLCODE_BY_TYPE_START',
    GET_ALLCODE_BY_TYPE_SUCCESS: 'GET_ALLCODE_BY_TYPE_SUCCESS',
    GET_ALLCODE_BY_TYPE_FAIL: 'GET_ALLCODE_BY_TYPE_FAIL',
    //Film
    CREATE_FILM_START: 'CREATE_FILM_START',
    CREATE_FILM_SUCCESS: 'CREATE_FILM_SUCCESS',
    CREATE_FILM_FAIL: 'CREATE_FILM_FAIL',
    
    FETCH_FILM_START: 'FETCH_FILM_START',
    FETCH_FILM_SUCCESS: 'FETCH_FILM_SUCCESS',
    FETCH_FILM_FAIL: 'FETCH_FILM_FAIL',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
})

export default actionTypes;